version: '3'
services:
  rtpproxy:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    entrypoint:
      - rtpproxy
      - -F
      - -f
      - -s
      - "udp:127.0.0.1:12222"
      #- -l
      #- "192.168.1.10"
      - -l
      - "171.244.138.13"
      - -m
      - "10000"
      - -M
      - "20000"
      - -d
      - "DBUG:LOG_LOCAL2"
      #- "INFO"
